Milestone : Review following JS best practices 🧐
ahmedeid6842/Code_Review_Exercise pull request #1
Opened 2023-06-12 20:12 UTC by ahmedeid6842

# Developing a Web-Based Todo List for Task Management :memo: :heavy_check_mark:

I would greatly appreciate your expertise in reviewing my work on the To-Do List :pray:. The goal of the project was to develop a user-friendly website for organizing daily tasks using ES6 and Webpack. :100: :ok_hand: 

### General Requirements :robot: 
- Ensured there were no linter errors.
- Followed the correct GitHub Flow.
- Documented the work in a professional manner.
- Followed best practices for HTML and CSS.
- Followed best practices for JavaScript.

### Done :mega:  :memo: 
- [x] Established the project with Webpack.
- [x] Developed an HTML structure with a placeholder for the To-Do List.
- [x] Dynamically populated the list from an array of tasks in the local storage. _At_ [_displayTask.js_](../blob/review_exercise/src/modules/displayTask.js) :eyes: 
 ```js 
 const tasksDisplay = () => {
  if (JSON.parse(localStorage.getItem('taskList'))) {
    Task.tasks = JSON.parse(localStorage.getItem('taskList'));
  }

  Task.tasks.forEach((task) => {
   // build HTML card for task
  });
  completeTask();
};
 ```
- [x] Applied CSS styling to the To-Do List.
- [x] Refactored the tasks array to eliminate hardcoded items.
- [x] Implemented functions for  [create](../blob/review_exercise/src/modules/createTask.js) , [edit](../blob/review_exercise/src/modules/editTask.js) and [delete](../blob/review_exercise/src/modules/deleteTask.js) tasks.
 - [x] Managed task indexes dynamically and updated them upon deletion.
- [x] Incorporated local storage to save changes. _At_ [_Task.js_](../blob/review_exercise/src/modules/Task.js) :eyes: 
 ```js 
 export default class Task {
  // classes methods
 
 // methods to mange localstorage
  static storageManagement(task) {
    localStorage.setItem('taskList', JSON.stringify(task));
  }
}

 ```
- [x] Created a new JavaScript Class to manage List static methods.
- [x] Added an event listener `change` for task completion checkboxes.
- [x] Implemented functionality for the "Clear all completed" button using the `filter` method.
- [x] Stored the updated task list in local storage.

## Screenshots GIFs 📸 🎥 

### Create Tasks :heavy_plus_sign: 
![chrome-capture-2023-5-7](https://github.com/ahmedeid6842/ToDo-List/assets/57197702/cea1654a-c9c6-4c6a-8613-9ce6b87580df)

### Delete Tasks :wastebasket: 
![chrome-capture-2023-5-8](https://github.com/ahmedeid6842/ToDo-List/assets/57197702/3a82845b-cb5f-465a-a3f1-9f2fa19fdf83)

### Update Tasks ✍️

![chrome-capture-2023-5-8 (1)](https://github.com/ahmedeid6842/ToDo-List/assets/57197702/d6103d05-cdf8-4d63-86c6-8626ca78d242)

### Clear Completed Tasks :wastebasket: 

![chrome-capture-2023-5-8 (2)](https://github.com/ahmedeid6842/ToDo-List/assets/57197702/be5c02f0-9d25-4525-adcb-8304a428f28c)

2023-06-12 21:17 UTC, ClaudiaRojasSoto requested changes
### Hi @ahmedeid6842 ✋ 
Ahmed, you definitely did a great job. This is evident from the very beginning by seeing:

## Highlights 🥇 
-The descriptive readme
-The professional commits
-Using good practices in HTML, CSS, and JavaScript
I really congratulate you. However, since nothing is perfect, there are a couple of things that you could improve. 

![congrats](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)

I left the comments below. Please let me know if you have any questions, and we can gladly clarify them.
I look forward to seeing the improvements in your project.

2023-06-12 21:17 UTC, ClaudiaRojasSoto commented on src/modules/completeTask.js
> +};
In the completeTask.js file, there is a reference to Task.storageManagement(Task.tasks) which should be moved inside the boxChangeHanlder function to avoid unnecessary calls to storageManagement when the task state does not change. It could look like this, for example:

const boxChangeHanlder = (event) => {
  const targetID = parseInt(event.target.parentNode.parentNode.className.split(' ')[1], 10) - 1;
  if (event.target.checked) {
    event.target.nextElementSibling.classList.add('done');
    Task.tasks[targetID].completed = true;
  } else if (!event.target.checked) {
    event.target.nextElementSibling.classList.remove('done');
    Task.tasks[targetID].completed = false;
  }
  Task.storageManagement(Task.tasks); // Mantener la llamada a storageManagement aquí
};

2023-06-13 04:27 UTC, ahmedeid6842 commented on src/modules/completeTask.js
> +};
Thank you @ClaudiaRojasSoto, for your comment! I made the changes you suggested and I think my code is now much cleaner. :pray:

2023-06-13 04:30 UTC, ahmedeid6842 commented on src/modules/editTask.js
> +};
### I did :heavy_check_mark: :heavy_check_mark: 
I really appreciate your help and guidance @ClaudiaRojasSoto. Let me know if you have any further comments or suggestions. Thanks again!

2023-06-13 14:59 UTC, ClaudiaRojasSoto approved these changes
Hi again @ahmedeid6842 ✋:
Your project is 💯 ... And of course APPROVED
You have done a great job so far!
There is nothing else to say than... It´s time to merge!! 

![congrats](https://media.giphy.com/media/l44Q6Etd5kdSGttXa/giphy.gif)

2023-06-13 22:03 UTC, merged

2023-06-13 22:50 UTC, ahmedeid6842 commented
Thanks @ClaudiaRojasSoto for your time and effort you take on reviewing. :pray: